config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end

  get 'homes/top'
  root 'homes#top'

  namespace 'admins' do
    resources :genres, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index]
    resources :ramenshops, only: [:new, :index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index]
  end

  namespace 'users' do
    resources :users, only: [:new, :create, :edit, :update, :show]
    resources :posts, only: [:new, :create, :index, :edit, :update, :destroy, :show]
    resources :ramenshops, only: [:index, :show] do
      resource :nices, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :genre, optional: true
  has_many :nices, dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def already_nice?(ramenshop)
    self.nices.exists?(ramenshop_id: ramenshop.id)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
    def index
        @users = User.all
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/nices_controller.rb
class Users::NicesController < ApplicationController
    def create
        @nice = current_user.nices.create(ramenshop_id: params[:ramenshop_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @ramenshop = Ramenshop.find(params[:ramenshop_id])
        @nice = current_user.nices.find_by(ramenshop_id: @ramenshop.id)
        @nice.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
    def new
        @post = Post.new
        @ramenshops = Ramenshop.all #(半径10km圏内)
        @genres = Genre.all
    end

    def create
        @post = Post.new(post_params)
        # binding.pry
        @post.user_id = current_user.id
        @post.save
        redirect_to users_posts_path(ramenshop_id: @post.ramenshop_id)
    end

    def index
        if params[:ramenshop_id] == nil
            @posts = Post.all
        else
            @posts = Post.where(ramenshop_id: params[:ramenshop_id])
        end
        @stores = Post.joins(:ramenshop).group("ramenshops.name").order('count_all DESC').count
        # byebug
    end

    def destroy
        @post = Post.find(params[:id])
        @post.delete
        redirect_to users_posts_path
    end

    private
    def post_params
        params.require(:post).permit(
            :ramenshop_id,
            :user_id,
            :genre_id,
            :name,
            :submenu,
            :comment,
            :score,
            :image)
    end
end

app/controllers/users/ramenshops_controller.rb
class Users::RamenshopsController < ApplicationController
  def index
    @posts = Post.group(:ramenshop_id).count
    @ramenshops = Ramenshop.all
  end
  
  def show
    @ramenshop = Ramenshop.find(params[:id])
    @posts = Post.where(ramenshop_id: @ramenshop.id).order(updated_at: :desc)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/supporters_controller.rb
class Users::SupportersController < ApplicationController
    def index
        @supporter = Supporter.new
        render :action => 'index'
    end
    
    def confirm
        @supporter = Supporter.new(params[:supporter])
        if @supporter.valid?
            render :action => 'confirm'
        else
            render :action => 'indes'
        end
    end
    
    def thanks
        @supporter = Supporter.new(params[:supporter])
        SupporterMailer.received_email(@supporter).deliver
        render :action => 'thanks'
    end
    
    
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
    @genres = Genre.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    UserMailer.published_email(@user).deliver
    redirect_to users_user_path(@user)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(genre_id: @user.genre_id)
    # byebug
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :genre_id)
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/nices_helper.rb
module Users::NicesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/ramenshops_helper.rb
module Users::RamenshopsHelper
end

app/helpers/users/supporters_helper.rb
module Users::SupportersHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/users/edit.html.erb
<div class="container">
    <div class="row">
        <%= form_with model: @user, url: users_user_path(@user), local: true do |f| %>
        <h3><%= current_user.name %>さんの情報</h3>
        <div class="table table-striped">
            <tr><td>好きな種類を選んでね：</td><td><%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "応援する種類を選択してください" %></td></tr></br>
            <tr><td>ネーム：</td><td><%= f.text_field :name, placeholder: "ニックネームでもいいよ", style: "border: none" %></td></tr></br>
            <tr><td>メール：</td><td><%= f.email_field :email, placeholder: "変えてもいいよ", style: "border: none" %></td></tr></br>
            <%= f.submit "分類や内容を変える" %>
            <%= link_to "やっぱ変えん", users_user_path(@user) %>
        </div>
        </div>
        <% end %>
    </div>
</div>

app/views/users/users/show.html.erb
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes">
</head>

<div class="container">
    <div class="row">
        <%= form_with model: @user, url: users_user_path(@user), local: true do |f| %>
        <% if @user.genre_id == nil %>
            <h3>好きなジャンルは無いのですね、<%= current_user.name %>さん</h3>
            <%= link_to "好きなジャンルを選びたい", edit_users_user_path(@user), class: "btn btn-success" %>
        <% else %>
            <h3><%= @user.genre.name %>を応援する<%= current_user.name %>さんの情報</h3>
            <%= link_to "好きなジャンルを変更する", edit_users_user_path(@user), class: "btn btn-success" %>
            <%= link_to "いいたかことがある", new_users_post_path, class: "btn btn-danger" %>
        <% end %>
    </div>
    <% end %>
    <div class="subtitle"><h4>貴方の応援する「<%= @user.genre.name %>」コメント一覧</h4></div></br></br>
    
    <!--<div class="col-xs-3 col-sm-12">-->
        <div class="card" style="width: auto;">
            <% @posts.each do |post| %>
            <!--<svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%", image="<%#= attachment_image_tag post, :image, format: 'jpg', fallback: "no_image.jpg", size: "50x50" %>"/></svg>-->
            <div class="card-body">
                <%= attachment_image_tag post, :image, format: 'jpg', fallback: "no_image.jpg", size: "200x200" %>
                <h5 class="card-title"><%= post.ramenshop.name %></h5>
                <p class="card-text"><%= post.comment %></p>
                <a href="#" class="btn btn-primary"><%= post.user.name %>様(投稿数：<%= post.user.posts.count.to_s %>）</a>
            </div>
            <% end %>
        </div>        
    <!--</div>-->
</div>