config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end

  get 'homes/top'
  root 'homes#top'

  namespace 'admins' do
    resources :genres, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index]
    resources :ramenshops, only: [:new, :index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index]
  end

  namespace 'users' do
    resources :users, only: [:new, :create, :edit, :update, :show]
    resources :posts, only: [:new, :create, :index, :edit, :update, :destroy, :show]
    resources :ramenshops, only: [:index, :show] do
      resource :nices, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user
  belongs_to :ramenshop
  
  validates_uniqueness_of :ramenshop_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :ramenshop
  belongs_to :genre
  
  attachment :image
  
  enum submenu: {thats_all: 0,rice: 1, fried_rice: 2, gyouza: 3}
end

app/models/ramenshop.rb
class Ramenshop < ApplicationRecord
  has_many :nices, dependent: :destroy
  has_many :posts, dependent: :destroy

  attachment :image
end

app/models/supporter.rb
class Supporter < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :genre, optional: true
  has_many :nices, dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def already_nice?(ramenshop)
    self.nices.exists?(ramenshop_id: ramenshop.id)
  end
end

app/controllers/admins/ramenshops_controller.rb
class Admins::RamenshopsController < ApplicationController
  def index
    @ramenshop = Ramenshop.new
    @posts = Post.group(:ramenshop_id).count
    # byebug
    # @ramenshops = Ramenshop.all.left_joins(:posts).group(:ramenshop_id).select('ramenshops.*, COUNT(`posts`.`user_id`) AS posts_count')
    @ramenshops = Ramenshop.all
    # @posts = Post.all
  end

  def create
    @ramenshop = Ramenshop.new(ramenshop_params)
    @ramenshop.save
    redirect_to admins_ramenshops_path
  end

  def edit
    # byebug
    @ramenshop = Ramenshop.find(params[:id])
  end

  def update
    @ramenshop = Ramenshop.find(params[:id])
    @ramenshop.update(ramenshop_params)
    redirect_to admins_ramenshops_path
  end

  def destroy
    @ramenshop = Ramenshop.find(params[:id])
    @ramenshop.destroy
    redirect_to admins_ramenshops_path
  end

  private

  def ramenshop_params
    params.require(:ramenshop).permit(:name, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
        case resource
        when User
            edit_users_user_path(current_user)
        when Admin
            admins_ramenshops_path
        end
    end

    def after_sign_out_path_for(resource)
        # byebug
        case resource
        when :user
            root_path
        when :admin
             new_admin_session_path
        end
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [
          :name,
          :genre_id])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/nices_controller.rb
class Users::NicesController < ApplicationController
    def create
        @nice = current_user.nices.create(ramenshop_id: params[:ramenshop_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @ramenshop = Ramenshop.find(params[:ramenshop_id])
        @nice = current_user.nices.find_by(ramenshop_id: @ramenshop.id)
        @nice.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
    def new
        @post = Post.new
        @ramenshops = Ramenshop.all #(半径10km圏内)
        @genres = Genre.all
    end

    def create
        @post = Post.new(post_params)
        # binding.pry
        @post.user_id = current_user.id
        @post.save
        redirect_to users_posts_path(ramenshop_id: @post.ramenshop_id)
    end

    def index
        if params[:ramenshop_id] == nil
            @posts = Post.all
        else
            @posts = Post.where(ramenshop_id: params[:ramenshop_id])
        end
        @stores = Post.joins(:ramenshop).group("ramenshops.name").order('count_all DESC').count
        # byebug
    end

    def destroy
        @post = Post.find(params[:id])
        @post.delete
        redirect_to users_posts_path
    end

    private
    def post_params
        params.require(:post).permit(
            :ramenshop_id,
            :user_id,
            :genre_id,
            :name,
            :submenu,
            :comment,
            :score,
            :image)
    end
end

app/controllers/users/ramenshops_controller.rb
class Users::RamenshopsController < ApplicationController
  def index
    @posts = Post.group(:ramenshop_id).count
    @ramenshops = Ramenshop.all
  end
  
  def show
    @ramenshop = Ramenshop.find(params[:id])
    @posts = Post.where(ramenshop_id: @ramenshop.id).order(updated_at: :desc)
  end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/admins/ramenshops_helper.rb
module Admins::RamenshopsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/nices_helper.rb
module Users::NicesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/ramenshops_helper.rb
module Users::RamenshopsHelper
end

app/helpers/users/supporters_helper.rb
module Users::SupportersHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/ramenshops/edit.html.erb
<div class="container">
    <div class="row">
        <h3>ラーメンショップ編集</h3></br></br>
        <%= form_with model: @ramenshop, url: admins_ramenshop_path(@ramenshop), local: true do |f| %>
        <%= attachment_image_tag @ramenshop, :image, format: 'jpg', fallback: "no_image.jpg", size: "300x300" %>
        <%= f.attachment_field :image %>
        <tr class="box"><td>店舗名</td><td><%= f.text_field :name, :size=> "20" %></td></tr>
      <div class="switch_left"><%= f.submit "編集を保存する",  class:"btn btn-primary" %></div>
      <% end %>
  </div>
</div>

app/views/admins/ramenshops/index.html.erb
<div class="container">
    <div class="row">
        <h3>ラーメンショップ</h3></br></br>
        <%= form_with model: @ramenshop, url: admins_ramenshops_path, local: true do |f| %>
        <div class="ramenshopnew">
            ラーメン店名
            <%= f.text_field :name %>
            <%= f.submit '追加', class: 'btn btn-primary' %>
        </div>
        <% end %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">ラーメン店名</th>
                    <th scope="col">投稿数</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <% @ramenshops.each do |ramenshop| %>
                <tr>
                    <td scope="row"><%= attachment_image_tag ramenshop, :image, format: 'jpg', fallback: "no_image.jpg", size: "50x50" %></td>
                    <td scope="row"><%= ramenshop.name %></td>
                    <td scope="row"><%= ramenshop.posts.count %></td>
                    <td><%= link_to "編集", edit_admins_ramenshop_path(ramenshop), class: "btn btn-success" %></td>
                    <td><%= link_to "削除", admins_ramenshop_path(ramenshop), method: :delete, data: { confirm: "本当に削除しますか？"}, class: "btn btn-danger" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>