config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end

  get 'homes/top'
  root 'homes#top'

  namespace 'admins' do
    resources :genres, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index]
    resources :ramenshops, only: [:new, :index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index]
  end

  namespace 'users' do
    resources :users, only: [:new, :create, :edit, :update, :show]
    resources :posts, only: [:new, :create, :index, :edit, :update, :destroy, :show]
    resources :ramenshops, only: [:index, :show] do
      resource :nices, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user
  belongs_to :ramenshop
  
  validates_uniqueness_of :ramenshop_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :ramenshop
  belongs_to :genre
  
  attachment :image
  
  enum submenu: {thats_all: 0,rice: 1, fried_rice: 2, gyouza: 3}
end

app/models/ramenshop.rb
class Ramenshop < ApplicationRecord
  has_many :nices, dependent: :destroy
  has_many :posts, dependent: :destroy

  attachment :image
end

app/models/supporter.rb
class Supporter < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :genre, optional: true
  has_many :nices, dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def already_nice?(ramenshop)
    self.nices.exists?(ramenshop_id: ramenshop.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
        case resource
        when User
            edit_users_user_path(current_user)
        when Admin
            admins_ramenshops_path
        end
    end

    def after_sign_out_path_for(resource)
        # byebug
        case resource
        when :user
            root_path
        when :admin
             new_admin_session_path
        end
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [
          :name,
          :genre_id])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/nices_helper.rb
module Users::NicesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/ramenshops_helper.rb
module Users::RamenshopsHelper
end

app/helpers/users/supporters_helper.rb
module Users::SupportersHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoveRamen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/35ef487505.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
        <nav class="nav navbar-nav navbar-left">
          <span class="title">しぇからしか〜、ラーメン<%= link_to "屋", new_admin_session_path %>行くばい</span>
          <% if user_signed_in? %>
            <span class="user"></br>　　　　　<%= current_user.name %>様、ようこそ LoveRamenへ！</span>
          <% elsif admin_signed_in? %>
            <span class="user"></br>　　　　　お仕事ご苦労様！</span>
          <% else %>
            <span class="user"></br>　　　　　</span>
          <% end %>
        </nav>
       <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Home", users_user_path(current_user), {class: "glyphicon glyphicon-home home"} %></li>
              <li><%= link_to "ラーメンショップ", users_ramenshops_path, {class: "glyphicon glyphicon-cutlery cutlery"} %></li>
              <li><%= link_to "投稿", new_users_post_path, {class: "glyphicon glyphicon-flash flash"} %></li>
              <li><%= link_to "投稿一覧", users_posts_path, {class: "glyphicon glyphicon-book book"} %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out log-out" %></li>
            <% elsif admin_signed_in? %>
              <li><%= link_to "分類", admins_genres_path, {class: "glyphicon glyphicon-home home"} %></li>
              <li><%= link_to "ラーメンショップ", admins_ramenshops_path, {class: "glyphicon glyphicon-cutlery cutlery"} %></li>
              <li><%= link_to "ユーザー", admins_users_path, {class: "glyphicon glyphicon-book book"} %></li>
              <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "glyphicon glyphicon-log-out log-out" %></li>
            <% else%>
              <li><%= link_to "Home", root_path, {class: "glyphicon glyphicon-home home"} %></li>
              <li><%= link_to "ログイン", new_user_session_path, {class: "glyphicon glyphicon-log-in log-in"} %></li>
              <li><%= link_to "サインアップ", new_user_registration_path, {class: "glyphicon glyphicon-log-in log-in"} %></li>
            <% end %>
          </ul>
        </nav>
    </header>
    <%= yield %>
    <footer>
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight LoveRamen</p>
    	</div>
    </footer>
  </body>
</html>